const Categories = [
  {
    id: 1,
    series: 1,
    name: "mr squiggles",
    desc: "Mr Squiggles is brown and white with a pink nose",
    price: 220,
    image: "../image/mrsquiggles.jpg",
  },
  {
    id: 2,
    series: 1,
    name: "pipsqueak",
    desc: "Pipsqueak is yellow and white with a pink nose",
    price: 200,
    image: "../image/pipsqueak.jpg",
  },
  {
    id: 3,
    series: 2,
    name: "jilly",
    desc: "Jilly is pink and white with a pink nose",
    price: 200,
    image: "../image/jilly.jpg",
  },
  {
    id: 4,
    series: 3,
    name: "moo",
    desc: "Moo is black and white with a pink nose",
    price: 200,
    image: "../image/moo.jpg",
  },
  {
    id: 5,
    series: 4,
    name: "jinx",
    desc: "Jinx is grey and white with a pink nose",
    price: 200,
    image: "../image/jinx.jpg",
  },
  {
    id: 6,
    series: 5,
    name: "dezel",
    desc: "Dezel is black and white with a pink nose",
    price: 200,
    image: "../image/dezel.jpg",
  },
  {
    id: 7,
    series: 6,
    name: "harlow",
    desc: "Harlow is green and white with a pink nose",
    price: 200,
    image: "../image/harlow.jpg",
  },
  {
    id: 8,
    series: 7,
    name: "pookie",
    desc: "Pookie is light pink and dark pink, with a pink nose",
    price: 200,
    image: "../image/pookie.jpg",
  },
  {
    id: 9,
    series: 8,
    name: "yoyo",
    desc: "Yoyo is grey with a pink nose",
    price: 200,
    image: "../image/yoyo.jpg",
  },
];
export default Categories;
