const Categories = [
  {
    id: 1,
    series: 1,
    name: "Mr Squiggles",
    desc: "Mr Squiggles is ...",
    price: 220,
    image: "../image/mrsquiggles.jpg",
  },
  {
    id: 2,
    series: 1,
    name: "Pipsqueak",
    desc: "Pipsqueak is ...",
    price: 200,
    image: "../image/pipsqueak.jpg",
  },
  {
    id: 3,
    series: 2,
    name: "Jilly",
    desc: "Jilly is ...",
    price: 200,
    image: "../image/jilly.jpg",
  },
  {
    id: 4,
    series: 3,
    name: "Moo",
    desc: "Moo is ...",
    price: 200,
    image: "../image/moo.jpg",
  },
  {
    id: 5,
    series: 4,
    name: "Jinx",
    desc: "Jinx is ...",
    price: 200,
    image: "../image/jinx.jpg",
  },
  {
    id: 6,
    series: 5,
    name: "Dezel",
    desc: "Dezel is ...",
    price: 200,
    image: "../image/dezel.jpg",
  },
  {
    id: 7,
    series: 6,
    name: "Harlow",
    desc: "Harlow is ...",
    price: 200,
    image: "../image/harlow.jpg",
  },
  {
    id: 8,
    series: 7,
    name: "Pookie",
    desc: "Pookie is ...",
    price: 200,
    image: "../image/pookie.jpg",
  },
  {
    id: 8,
    series: 8,
    name: "Yoyo",
    desc: "Yoyo is ...",
    price: 200,
    image: "../image/yoyo.jpg",
  },
];
export default Categories;
